stages:
  - build
  - deploy



build:
  stage: build

  only:
  - master

  script:
    - yarn
    - yarn ng build --prod --optimization

  artifacts:
    paths:
      - ./dist/



deploy:
  stage: deploy

  only:
    - master

  variables:
    dir_root: /var/www/
    webspace: finnthorben/

  script:
    - "target=$dir_root$webspace"
    - "echo \"Deploying to: $target\""
    - "rsync -rlvc --delete --chown gitlab-runner:www-data ./dist/homepage/ $target"
