stages:
  - deploy

deploy:
  when: manual
  stage: deploy

  variables:
    dir_root: /var/www/
    webspace: finnthorben/

  script:
    - "target=$dir_root$webspace"
    - "echo 'Deploying to: $target'"