---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: www-finn-thorben-me
commonLabels:
  app.kubernetes.io/part-of: www.finn-thorben.me

resources:
  - k8s/namespace.yml
  - k8s/deployment.yml
  - k8s/service.yml
