steps:
  - name: check-pre-commit
    depends_on: []
    when:
      - event: push
      - event: cron
      - event: manual
    image: git.lly.sh/ftsell/lillinfra-pre-commit
    volumes:
      - woodpecker-cache:/woodpecker/src/cache
    environment:
      XDG_CACHE_HOME: /woodpecker/src/cache
      DEBIAN_FRONTEND: noninteractive
    commands:
      - pre-commit run --show-diff-on-failure --all-files

  - name: test-django-server
    depends_on: []
    when:
      - event: push
      - event: cron
      - event: manual
    image: docker.io/debian
    volumes:
      - woodpecker-cache:/woodpecker/src/cache
    environment:
      XDG_CACHE_HOME: /woodpecker/src/cache
      DEBIAN_FRONTEND: noninteractive
    commands:
      - |
        apt update
        apt install -y --no-install-recommends python3 python3-pip
      - pip install --break-system-packages --editable .[dev]
      - pytest
